from talon.voice import Context, Key

ctx = Context("symbol")

keymap = {
    "question [mark]": "?",
    "(minus | dash)": "-",
    "plus": "+",
    "tilde": "~",
    "(bang | exclamation point | clamor)": "!",
    "(dollar [sign] | dolly)": "$",
    "downscore": "_",
    "(semi | semicolon | sunk)": ";",
    "colon": ":",
    "(square | left square [bracket] | brackorp)": "[",
    "(rsquare | are square | right square [bracket] | brackose)": "]",
    "(paren | left paren | precose)": "(",
    "(rparen | are paren | right paren)": ")",
    "(brace | left brace)": "{",
    "(rbrace | are brace | right brace)": "}",
    "(angle | left angle | less than)": "<",
    "(rangle | are angle | right angle | greater than)": ">",
    "(star | asterisk)": "*",
    "(pound | hash [sign] | octo | number sign)": "#",
    "percent [sign]": "%",
    "caret": "^",
    "at sign": "@",
    "(and sign | ampersand | amper)": "&",
    "(pipe | spike)": "|",
    "(D pipe)": " | ",
    "(dubquote | double quote)": '"',
    "(quote | quatchet)": "'",
    "triple quote": "'''",
    "tick": "`",
    "triple tick": "```",
    "(dot | period)": ".",
    "(dot dot | dotdot)": "..",
    "(dot dot dot | dotdotdot)": "...",
    "comma": ",",
    "swipe": ", ",
    "coalgap": ": ",
    "skoosh": " ",
    "[forward] slash": "/",
    "[forward] slasher": "// ",
    "[forward] dubslash": "//",
    "backslash": "\\",
    "coalshock": [":", Key("enter")],
    "coal twice": "::",
    "ellipsis": "...",
    "mintwice": "--",
    "plustwice": "++",
    # equality
    "coleek": " := ",
    "empty dict": "{}",
    "minquall": "-=",
    "pluqual": "+=",
    "starqual": "*=",
    "lessqual": " <= ",
    "grayqual": " >= ",
    "smaqual": "=",
    "equeft": " = ",
    "([is] equal to | longqual)": " == ",
    "([is] not equal to | banquall)": " != ",
    "(trickle | triple equal)": " === ",
    "(ranqual | nockle)": " !== ",
    "(arrow | lambo)": " -> ",
    "shrocket": " => ",
    "sinker": [Key("cmd-right ;")],
    # surrounders
    "empty array": "[]",
    "and sign": "&",
    "(dot dot | dotdot | doodle)": "..",
    "enter": Key("enter"),
}

ctx.keymap(keymap)
